trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: run_tests
  steps:
  - script: 
      ./install.sh
    displayName: 'Run Setup Script'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10.6'
      addToPath: true

  - script: |
      pip install .[dev]
    displayName: 'Install Python Package'

  - script: |
      pytest -s -m auto --log-cli-level=DEBUG tests/test_end_to_end.py
    displayName: 'Run pytest'
