site_name: pyplanqk documentation
repo_url: https://github.com/PlanQK/pyplanqk
repo_name: PlanQK/pyplanqk
edit_uri: edit/master/docs

theme:
  name: "material"
  homepage: https://planqk.de/
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - toc.follow
    - content.action.edit

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "google"
  - git-committers:
      enabled: true
      repository: PlanQK/pyplanqk
      branch: master
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
