[build-system]
requires = ["setuptools"]

[project]
name = "pyplanqk"
authors = [{ name = "Henning Krause", email = "henning.krause@gft.com" }, ]
description = ""
requires-python = ">=3.10.6"
dependencies = [
    "pytest",
    "numpy",
    "requests",
    "python-dateutil",
    "urllib3"
]
dynamic = ["version"]


[tool.pytest.ini_options]
markers = [
    "previously_wrong: only run previously wrong tests",
    "interactive: only run tests with user interaction",
    "slow_service: only run tests wich are slow because of the service creation",
]
log_cli = true
log_cli_level = "DEBUG"