
name: mkdocs 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install "mkdocstrings==0.22.0" "mkdocstrings-python==1.3.*" "mkdocs-material==9.5.10", "mkdocs-git-committers-plugin-2==2.2.3", "mkdocs-git-revision-date-localized-plugin==1.2.4"
      - run: mkdocs gh-deploy --force
